version: "3.7"
services:
  app:
    image: harmonia/fedavg
    environment:
      OPERATOR_URI: operator:8787
    volumes:
      - type: volume
        source: shared
        target: /repos
  operator:
    image: harmonia/operator
    volumes:
      - ./config.yml:/app/config.yml
      - type: volume
        source: shared
        target: /repos
    networks:
      mnist:
        aliases:
          - aggregator
      default:
networks:
  mnist:
    external:
      name: mnist
volumes:
  shared:
